endpoint:
  url: http://localhost:8080/swagger
  method: GET
  timeout: 0.010
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
cachet:
  api_url: http://status.cachethq.io/api/v1/
  token: my_token
  component_id: 1
  metric_id: 1
frequency: 30
